# ansible-playbook nginx_controller_gateway.yaml -e "user_email=brian@example.com user_password=notsecure controller_fqdn=controller.example.local" 
# ansible-playbook nginx_controller_gateway.yaml -e "@nginx_controller_gateway_vars.yaml"

- hosts: localhost
  gather_facts: no

  tasks:
  - include_role:
      name: nginxinc.nginx_controller.nginx-controller-generate-token

  - name: configure the gateway
    include_role:
      name: nginxinc.nginx_controller.nginx-controller-gateway
