# ansible-playbook nginx_controller_gateway.yaml -e "user_email=brian@example.com user_password=notsecure controller_fqdn=controller.example.local" 
# ansible-playbook nginx_controller_gateway.yaml -e "@nginx_controller_gateway_vars.yaml"

- hosts: localhost
  gather_facts: no
  collections: 
  - nginxinc.nginx_controller

  tasks:
  - name: where am i
    debug:
    - msg: "present working directory: {{ pwd }}"
    - msg: "playbook directory: {{ playbook_dir }}"

  - include_role:
      name: nginx_controller_generate_token

  - name: configure the gateway
    include_role:
      name: nginx_controller_gateway
