# ansible-playbook nginx_controller_gateway.yaml -e "user_email=brian@example.com user_password=notsecure controller_fqdn=controller.example.local" 
# ansible-playbook nginx_controller_gateway.yaml -e "@nginx_controller_gateway_vars.yaml"

- hosts: localhost
  gather_facts: no
  collections: 
  - nginxinc.nginx_controller

  tasks:
  - debug:
      msg: '{{ lookup(nginxinc.nginx_controller.lookup1", 'param1')| nginxinc.nginx_controller.filter1 }}'

  - include_role:
      name: nginx-controller-generate-token

  - name: configure the gateway
    include_role:
      name: nginx-controller-gateway
